
import pygame


bone_0_0_image = pygame.image.load('images/bone_0_0.png')
bone_0_1_image = pygame.image.load('images/bone_0_1.png')
bone_0_2_image = pygame.image.load('images/bone_0_2.png')
bone_0_3_image = pygame.image.load('images/bone_0_3.png')
bone_0_4_image = pygame.image.load('images/bone_0_4.png')
bone_0_5_image = pygame.image.load('images/bone_0_5.png')
bone_0_6_image = pygame.image.load('images/bone_0_6.png')
bone_1_1_image = pygame.image.load('images/bone_1_1.png')
bone_1_2_image = pygame.image.load('images/bone_1_2.png')
bone_1_3_image = pygame.image.load('images/bone_1_3.png')
bone_1_4_image = pygame.image.load('images/bone_1_4.png')
bone_1_5_image = pygame.image.load('images/bone_1_5.png')
bone_1_6_image = pygame.image.load('images/bone_1_6.png')
bone_2_2_image = pygame.image.load('images/bone_2_2.png')
bone_2_3_image = pygame.image.load('images/bone_2_3.png')
bone_2_4_image = pygame.image.load('images/bone_2_4.png')
bone_2_5_image = pygame.image.load('images/bone_2_5.png')
bone_2_6_image = pygame.image.load('images/bone_2_6.png')
bone_3_3_image = pygame.image.load('images/bone_3_3.png')
bone_3_4_image = pygame.image.load('images/bone_3_4.png')
bone_3_5_image = pygame.image.load('images/bone_3_5.png')
bone_3_6_image = pygame.image.load('images/bone_3_6.png')
bone_4_4_image = pygame.image.load('images/bone_4_4.png')
bone_4_5_image = pygame.image.load('images/bone_4_5.png')
bone_4_6_image = pygame.image.load('images/bone_4_6.png')
bone_5_5_image = pygame.image.load('images/bone_5_5.png')
bone_5_6_image = pygame.image.load('images/bone_5_6.png')
bone_6_6_image = pygame.image.load('images/bone_6_6.png')
bone_back_image = pygame.image.load('images/bone_back.png')
